version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6

    working_directory: ~/tag-inflator

    steps:
      - checkout

      - run: pip install -r requirements.txt
      - run: wget https://april.eecs.umich.edu/media/apriltag/tag36h11.tgz
      - run: tar -xvf tag36h11.tgz
      - run: python3 inflate.py tag36h11
